/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_sell;

import static car_sell.DeleteCar_Interface.l;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Zakaria Nabil
 */
public class Declarer_Ventes_Interface extends javax.swing.JFrame {

 DefaultTableModel ml=new DefaultTableModel();


     List<Ventes>l=new  ArrayList <Ventes>();
  String []t={"Nom De L'acheteur","Numéro Cin","Date D'achat","Marque","Modele","Année","Kilométrage","Prix"};
   RowSorter<DefaultTableModel> sorter = new TableRowSorter<>(ml);
    /**
     * Creates new form Declarer_Ventes_Interface
     */
    public Declarer_Ventes_Interface() {
      
        initComponents(); 
        this.jTable1.setRowSorter(sorter);
         ml.setColumnIdentifiers(t);
         this.jTable1.setModel(ml);
       
         ////
         
         FileInputStream f=null;
              ObjectInputStream ff=null;
      
               try {
           
             f=new FileInputStream ("Liste Ventes Voitures.txt");
        } catch (FileNotFoundException ex) {
        }
       try {
          ff=new ObjectInputStream(f);
        } catch (IOException ex) {
        }
       
        try {
       l=(List<Ventes>)ff.readObject();
        SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
       for(Ventes e:l)
       {
        ml.addRow(new Object[]{e.getNom(),e.getNumcin(),df.format(e.getDateachat()),e.getMarque(),e.getModele(),e.getAnnee(),e.getKilometrage(),e.getPrix()});
 
        }} catch (IOException ex) {
        } catch (ClassNotFoundException ex) {
        }
        try {
            ff.close();
        } catch (IOException ex) {
            Logger.getLogger(Liste_Ventes_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_marque = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txt_modele = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_annee = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txt_date = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Déclarer Une Vente ");
        setMaximumSize(new java.awt.Dimension(1028, 499));
        setMinimumSize(new java.awt.Dimension(1028, 499));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nom Complet De L' acheteur :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 170, 30);

        txt_nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_nom);
        txt_nom.setBounds(40, 50, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Numéro De La CIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 20, 120, 20);

        txt_cin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cinActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cin);
        txt_cin.setBounds(230, 50, 130, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Date D'achat :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 20, 130, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Marque : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 100, 120, 30);

        txt_marque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_marque.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alfa Romeo", "Aston Martin", "Audi", "Bentley", "Bmw", "Chery", "Chevrolet", "Citroen", "Dacia", "Dodge", "Daihatsu", "Ferrari", "Fiat", "Ford", "Geely", "Honda", "Hyundai", "Isuzu", "Jaguar", "Jeep", "Kia", "Lamborghini", "Lexus", "Lancia", "Land Rover", "GMC", "Mini", "Maserati", "Mazda", "McLaren", "Mercedes", "Mitsubishi", "Nissan", "Opel", "Peugeot", "Porsche", "Renault", "Rover", "Seat", "Skoda", "Smart", "Ssangyong", "Subaru", "Suzuki", "Toyota", "Toyota", "Volkswagen", "Volvo", "Zotye" }));
        getContentPane().add(txt_marque);
        txt_marque.setBounds(40, 130, 150, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Modèle : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 100, 130, 30);

        txt_modele.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_modele);
        txt_modele.setBounds(230, 130, 140, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Année :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 100, 130, 30);

        txt_annee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_annee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981" }));
        getContentPane().add(txt_annee);
        txt_annee.setBounds(420, 130, 140, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Kilométrage : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 190, 150, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Prix : ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 190, 120, 20);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Ajouter a La Liste Des Ventes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 280, 320, 50);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Enregistrer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 340, 320, 50);

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### ###  Km")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(230, 210, 150, 40);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###  Km")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(230, 210, 150, 40);

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###  Km")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(230, 210, 150, 40);

        try {
            jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###  Km")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField4);
        jFormattedTextField4.setBounds(230, 210, 150, 40);

        try {
            jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.### Dhs")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField5);
        jFormattedTextField5.setBounds(40, 210, 150, 40);

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Return");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 0, 90, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom ", "Num CIN", "Date D'achat", "Marque", "Modèle", "Année", "Prix", "Kilométrage"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(322, 280, 700, 210);

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(760, 0, 72, 20);

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Supprimer");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(860, 250, 160, 30);
        getContentPane().add(txt_date);
        txt_date.setBounds(423, 50, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_sell/Banner for car selling program zakka.jpg"))); // NOI18N
        jLabel1.setEnabled(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
         String  nom=this.txt_nom.getText();
         String cin = this.txt_cin.getText();
         Date dateachat = this.txt_date.getDate();
         String  marque=(String) this.txt_marque.getSelectedItem();
         String modele = this.txt_modele.getText();
         String year = (String) this.txt_annee.getSelectedItem();
         String kilometrage=(this.jFormattedTextField2.getText());
         String prix =(this.jFormattedTextField5.getText());
         

       
        boolean b=true;    
      
         
      
        if(this.jFormattedTextField2.getText().equals("")||this.txt_modele.getText().equals("")||this.txt_marque.getSelectedItem()==null||this.jFormattedTextField5.getText().equals("")||this.txt_annee.getSelectedItem()==null)

        { JOptionPane.showMessageDialog(this,"Veuillez Remplir Tous Les Champs","Erreur Lors De La Saisie",JOptionPane.ERROR_MESSAGE);}

        Pattern pattern = Pattern.compile("[0-9]*");
        Matcher matcher = pattern.matcher(this.jFormattedTextField5.getText());
       
             SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");

     
    
         {
           Ventes  e= new Ventes(nom,cin,dateachat,marque,modele,year,kilometrage,prix);
          l.add(e);
            ml.addRow(new Object[]{e.getNom(),e.getNumcin(),df.format(e.getDateachat()),e.getMarque(),e.getModele(),e.getAnnee(),e.getKilometrage(),e.getPrix()});
        }
          //// Save
          FileOutputStream f=null;
        ObjectOutputStream ff=null;
    try
        {
            f=new FileOutputStream ("Liste Ventes Voitures.txt");
            ff= new ObjectOutputStream(f);
           ff.writeObject(l);
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        finally
        {
            try {
                 
                ff.close();
                JOptionPane.showMessageDialog(this, "Enregistrement Effectué Dans Le Fichier ","Sauvegarde réussie", JOptionPane.INFORMATION_MESSAGE);
                 
           }catch (IOException ex) {
            }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Facture_Vente f = new Facture_Vente();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jFormattedTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Vendor_Interface v = new Vendor_Interface();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.txt_nom.setText(null);
        this.txt_cin.setText(null);
        txt_date.setDate(null);
        txt_marque.setSelectedIndex(0);
        txt_modele.setText(null);
        jFormattedTextField2.setText(null);
        jFormattedTextField5.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  int ligneselectionne=this.jTable1.getSelectedRow();
        int rep=JOptionPane.showConfirmDialog(this, "Étes Vous Sur De Vouloir Supprimer Cette Vente Du Système ?","Suppression",JOptionPane.YES_NO_OPTION);
        if(rep==JOptionPane.YES_OPTION) 
        {   ml.removeRow(ligneselectionne);
            l.remove(ligneselectionne);}
        //// Save
          FileOutputStream f=null;
        ObjectOutputStream ff=null;
    
        

        try
        {
            f=new FileOutputStream ("Liste Ventes Voitures.txt");
            ff= new ObjectOutputStream(f);
            ff.writeObject(l);
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        finally
        {
            try {
                 
                ff.close();
                
                 if(rep==JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Suppression Effectuée Avec Succés ","Suppression réussie", JOptionPane.INFORMATION_MESSAGE);
                 }
           }catch (IOException ex) {
            }
        
        }       
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Declarer_Ventes_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Declarer_Ventes_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Declarer_Ventes_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Declarer_Ventes_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Declarer_Ventes_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public static javax.swing.JFormattedTextField jFormattedTextField1;
    public static javax.swing.JFormattedTextField jFormattedTextField2;
    public static javax.swing.JFormattedTextField jFormattedTextField3;
    public static javax.swing.JFormattedTextField jFormattedTextField4;
    public static javax.swing.JFormattedTextField jFormattedTextField5;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JComboBox txt_annee;
    public static javax.swing.JTextField txt_cin;
    public static com.toedter.calendar.JDateChooser txt_date;
    public static javax.swing.JComboBox txt_marque;
    public static javax.swing.JTextField txt_modele;
    public static javax.swing.JTextField txt_nom;
    // End of variables declaration//GEN-END:variables
}
