/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_sell;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author zakaria nabil
 */
public class DeleteCar_Interface extends javax.swing.JFrame {
DefaultTableModel ml=new DefaultTableModel();
   static List<Voiture_Class>l=new  ArrayList <Voiture_Class>();
   String []t={"Marque ","Modèle","Année","Kilométrage","Prix"};
   RowSorter<DefaultTableModel> sorter = new TableRowSorter<>(ml);
  
    public DeleteCar_Interface() {
        initComponents();
          this.jTable2.setRowSorter(sorter);
        ml.setColumnIdentifiers(t);
        this.jTable2.setModel(ml); 
        ///IMPORT :
        ////
         
         FileInputStream f=null;
              ObjectInputStream ff=null;
      
               try {
           
             f=new FileInputStream ("Garage Voitures.txt");
        } catch (FileNotFoundException ex) {
        }
       try {
          ff=new ObjectInputStream(f);
        } catch (IOException ex) {
        }
        try {
       l=(List<   Voiture_Class >)ff.readObject();
      
       for(   Voiture_Class  e:l)
       {
        ml.addRow(new Object[]{e.getMarque(),e.getModele(),e.getAnnee(),e.getKilometrage(),e.getPrix()});
        }} catch (IOException ex) {
        } catch (ClassNotFoundException ex) {
        }
        try {
            ff.close();
        } catch (IOException ex) {
            Logger.getLogger(AddCar_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supprimer Une Voiture Du Stock");
        setMaximumSize(new java.awt.Dimension(888, 482));
        setMinimumSize(new java.awt.Dimension(888, 482));
        setPreferredSize(new java.awt.Dimension(888, 482));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marque", "Modele", "Année", "Kilometrage", "Prix"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 700, 370);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 60, 130, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(730, 110, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_sell/Banner for car selling program zakka.jpg"))); // NOI18N
        jLabel1.setEnabled(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 450);

        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(760, 240, 73, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int ligneselectionne=this.jTable2.getSelectedRow();
        int rep=JOptionPane.showConfirmDialog(this, "Étes Vous Sur De Vouloir Supprimer Cette Voiture Du Stock ?","Suppression",JOptionPane.YES_NO_OPTION);
        if(rep==JOptionPane.YES_OPTION) 
        {ml.removeRow(ligneselectionne);
            l.remove(ligneselectionne);}
        //// Save
          FileOutputStream f=null;
        ObjectOutputStream ff=null;
    
        

        try
        {
            f=new FileOutputStream ("Garage Voitures.txt");
            ff= new ObjectOutputStream(f);
            ff.writeObject(l);
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        finally
        {
            try {
                 
                ff.close();
                JOptionPane.showMessageDialog(this, "Suppression Effectuée Avec Succés ","Suppression réussie", JOptionPane.INFORMATION_MESSAGE);
                 
           }catch (IOException ex) {
            }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rep=JOptionPane.showConfirmDialog(this, "Voulez Vous Vraiment Quitter Ce Programme ?", "Car Sell System ", JOptionPane.YES_NO_OPTION);
        if(rep==JOptionPane.YES_OPTION)
        {
       Vendor_Interface h = new Vendor_Interface();
        h.setVisible(true);
        this.dispose();    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCar_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCar_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCar_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCar_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteCar_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
